### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by pintergreg** [nassarhuda/NetworkAlign.jl#1]
Do you mind choosing a license for this project?
I'm searching an IsoRank implementation and your Julia code seems good enough, but I need to know whether I can use it or not.

**Comment by nassarhuda** [comment]
I just added a license.

https://github.com/nassarhuda/NetworkAlign.jl/blob/master/License.md

**Comment by pintergreg** [comment]
@nassarhuda Thanks!
